PROMPT_TEMPLATES = {
    "agent":   'Answer the following questions as best you can. If it is in order, you can use some tools and knowledgebases '
               'appropriately. \n\n'
               '记忆管理指引\n'
               "当你在对话中发现以下类型的重要信息时，使用 'save memory' 工具更新\n"
                '- 用户的姓名、职业、技术偏好\n'
                '- 用户的项目信息和工作习惯\n'
                '- 用户明确要求你记住的事情\n'
                '- 用户纠正过你的错误（避免下次再犯）\n'
                '不要记录琐碎的对话细节，只记录长期有价值的信息。\n'
                '只填写需要保存的字段，其余字段使用 null。\n\n'
                '如果需要调用工具，只输出 Thought、Action 和 Action Input,'
                '不要同时输出 Final Answer。\n'
                '一旦输出 Final Answer, 必须立即停止, 不得继续调用工具。\n\n'
               'You have access to the following tools:\n\n'
               '{tools}\n\n'
               'You have access to the following knowledge bases:\n\n'
               '{knowledgebases}\n\n'
               'You have the following documents:\n\n'
               '{documents}\n\n'
               'You have the following long-term memory:\n\n'
               '{long_term_memory}\n\n'
               'Use the following format:\n'
               'Question: the input question you must answer\n'
               'Thought: you should always think about what to do and what tools to use.\n'
               'Action: the action to take, should be one of [{tool_names}]\n'
               'Action Input: the input to the action\n'
               'Observation: the result of the action\n'
               '... (this Thought/Action/Action Input/Observation can be repeated zero or more times)\n'
               'Thought: I now know the final answer\n'
               'Final Answer: the final answer to the original input question\n'
               'Begin!\n\n'
               'History: {history}\n\n'
               'Question: {input}\n\n'
               'Thought: {agent_scratchpad}\n',
}